-- Archers Franchise Console • Phase One
-- Canon and Session Control
-- Safe to run more than once.

create table if not exists public.archers_franchise_state (
  id text primary key,
  version integer not null default 1 check (version > 0),
  state jsonb not null,
  source_checkpoint_id text not null,
  seal_status text not null default 'SEALED CANON',
  updated_at timestamptz not null default now()
);

create table if not exists public.archers_canon_events (
  event_id bigint generated by default as identity primary key,
  franchise_id text not null references public.archers_franchise_state(id) on delete cascade,
  state_version integer not null,
  event_type text not null,
  summary text not null,
  exact_kevin_text text,
  source_label text not null default 'LIVE_SESSION_LOG',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_archers_state_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists archers_franchise_state_updated_at
on public.archers_franchise_state;

create trigger archers_franchise_state_updated_at
before update on public.archers_franchise_state
for each row
execute function public.set_archers_state_updated_at();

create or replace function public.archers_jsonb_deep_merge(original jsonb, patch jsonb)
returns jsonb
language sql
immutable
set search_path = public
as $$
  select case
    when jsonb_typeof(original) <> 'object' or jsonb_typeof(patch) <> 'object'
      then patch
    else coalesce(
      (
        select jsonb_object_agg(key, value)
        from (
          select
            coalesce(a.key, b.key) as key,
            case
              when a.value is null then b.value
              when b.value is null then a.value
              when jsonb_typeof(a.value) = 'object' and jsonb_typeof(b.value) = 'object'
                then public.archers_jsonb_deep_merge(a.value, b.value)
              else b.value
            end as value
          from jsonb_each(original) a
          full join jsonb_each(patch) b using (key)
        ) merged
      ),
      '{}'::jsonb
    )
  end;
$$;

create or replace function public.apply_archers_state_update(
  p_patch jsonb,
  p_event_type text,
  p_summary text,
  p_exact_kevin_text text default null,
  p_source_label text default 'LIVE_SESSION_LOG'
)
returns table (
  version integer,
  state jsonb,
  updated_at timestamptz,
  event_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.archers_franchise_state%rowtype;
  merged_state jsonb;
  new_event_id bigint;
begin
  if p_patch is null or jsonb_typeof(p_patch) <> 'object' then
    raise exception 'patch must be a JSON object';
  end if;

  if coalesce(trim(p_event_type), '') = '' then
    raise exception 'event_type is required';
  end if;

  if coalesce(trim(p_summary), '') = '' then
    raise exception 'summary is required';
  end if;

  select *
  into current_row
  from public.archers_franchise_state
  where id = 'stl-2026'
  for update;

  if not found then
    raise exception 'Archers franchise state has not been initialized';
  end if;

  merged_state := public.archers_jsonb_deep_merge(current_row.state, p_patch);

  -- Mechanical canon guardrails.
  merged_state := jsonb_set(merged_state, '{franchise,team}', to_jsonb('St. Louis Archers'::text), true);
  merged_state := jsonb_set(merged_state, '{franchise,owner_and_general_manager}', to_jsonb('Kevin Dorey'::text), true);
  merged_state := jsonb_set(merged_state, '{canon,kevin_lock,enabled}', 'true'::jsonb, true);
  merged_state := jsonb_set(merged_state, '{canon,sync_status}', to_jsonb('Synced'::text), true);

  update public.archers_franchise_state
  set
    version = current_row.version + 1,
    state = merged_state
  where id = current_row.id
  returning public.archers_franchise_state.version,
            public.archers_franchise_state.state,
            public.archers_franchise_state.updated_at
  into version, state, updated_at;

  insert into public.archers_canon_events (
    franchise_id,
    state_version,
    event_type,
    summary,
    exact_kevin_text,
    source_label,
    payload
  )
  values (
    current_row.id,
    version,
    trim(p_event_type),
    trim(p_summary),
    nullif(p_exact_kevin_text, ''),
    coalesce(nullif(trim(p_source_label), ''), 'LIVE_SESSION_LOG'),
    p_patch
  )
  returning public.archers_canon_events.event_id into new_event_id;

  event_id := new_event_id;
  return next;
end;
$$;

alter table public.archers_franchise_state enable row level security;
alter table public.archers_canon_events enable row level security;

revoke all on table public.archers_franchise_state from anon, authenticated;
revoke all on table public.archers_canon_events from anon, authenticated;
revoke all on function public.apply_archers_state_update(jsonb, text, text, text, text) from public, anon, authenticated;

grant usage on schema public to anon, service_role;
grant select on table public.archers_franchise_state to anon, service_role;
grant select on table public.archers_canon_events to anon, service_role;
grant update on table public.archers_franchise_state to service_role;
grant insert on table public.archers_canon_events to service_role;
grant usage, select on sequence public.archers_canon_events_event_id_seq to service_role;
grant execute on function public.apply_archers_state_update(jsonb, text, text, text, text) to service_role;

drop policy if exists "Public console reads Archers state"
on public.archers_franchise_state;

create policy "Public console reads Archers state"
on public.archers_franchise_state
for select
to anon
using (id = 'stl-2026');

drop policy if exists "Public console reads Archers event ledger"
on public.archers_canon_events;

create policy "Public console reads Archers event ledger"
on public.archers_canon_events
for select
to anon
using (franchise_id = 'stl-2026');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'archers_franchise_state'
  ) then
    alter publication supabase_realtime add table public.archers_franchise_state;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'archers_canon_events'
  ) then
    alter publication supabase_realtime add table public.archers_canon_events;
  end if;
end
$$;

insert into public.archers_franchise_state (
  id,
  version,
  state,
  source_checkpoint_id,
  seal_status
)
values (
  'stl-2026',
  1,
  $archers_state$
{
  "franchise": {
    "team": "St. Louis Archers",
    "season": 2026,
    "season_label": "Inaugural season",
    "owner_and_general_manager": "Kevin Dorey",
    "head_coach": {
      "name": "Avery Holt",
      "pronouns": "she/her"
    },
    "record": {
      "wins": 2,
      "losses": 0,
      "division_wins": 2,
      "division_losses": 0,
      "central_position": "First place alone",
      "points_for": 65,
      "points_against": 6,
      "point_differential": 59
    }
  },
  "timeline": {
    "week": 3,
    "day": "Tuesday",
    "in_universe_date": "2026-09-22",
    "location": "St. Louis Archers Training Facility",
    "current_position": "Before Week Three practice-squad protections and before formal Baltimore preparation.",
    "exact_continuation_point": "Avery Holt has closed the Chicago file. Baltimore's logo appeared, but the team was explicitly told not to open Baltimore film until Tuesday. Aaron Whitlock put his tablet away. The next scene begins with Tuesday's Week Three practice-squad protection decision before formal Baltimore preparation."
  },
  "opponent": {
    "name": "Baltimore Admirals",
    "record": "2-0",
    "site": "Home",
    "kickoff_label": "Sunday, September 27, 2026 • 12:00 PM Central",
    "preparation_status": "Not opened; explicitly deferred until Tuesday.",
    "known_note": "Starting right guard Damon Kirkland's knee status remains unresolved. St. Louis will prepare as though he will play."
  },
  "canon": {
    "constitution": {
      "title": "Draft a Dynasty Constitution",
      "version": "First Ratified Edition",
      "status": "Governing"
    },
    "bible": {
      "title": "Draft a Dynasty Bible",
      "version": "1.1",
      "status": "Operational"
    },
    "checkpoint": {
      "id": "STL-2026-W02-CCP",
      "status": "SEALED CANON",
      "binding_through": "Monday, September 21, 2026 • 12:26 PM Central"
    },
    "sync_status": "Synced",
    "kevin_lock": {
      "enabled": true,
      "rule": "Never invent, extend, polish, paraphrase as dialogue, or complete Kevin Dorey's words, deliberate actions, promises, or explicit decisions. When Kevin needs to speak or act, stop and hand the scene to the user."
    },
    "dialogue_attribution_rule": "Every spoken line identifies the speaker by full name and current position or job.",
    "evidence_boundaries": [
      "The complete official final team and individual box score for Week Two remains UNRECOVERED and must not be invented.",
      "The formal Week Two inactive list remains incomplete. Malik Harlan did not participate; Nate Sinclair's game-day activation status remains UNRECOVERED."
    ]
  },
  "roster": {
    "active_count": 53,
    "practice_squad_count": 16,
    "week_three_protections_status": "Not selected",
    "transactions_status": "No Monday signing, waiver, release, promotion, or trade.",
    "elevations": [
      {
        "name": "Otto Mbeki",
        "position": "Tight End/H-Back",
        "used": 2,
        "remaining": 1,
        "status": "Practice squad; reverted after Week Two",
        "note": "Active-roster-quality H-back role validated; permanent-roster question approaching."
      },
      {
        "name": "Teo Branković",
        "position": "Defensive Tackle",
        "used": 1,
        "remaining": 2,
        "status": "Practice squad; reverted after Week Two",
        "note": "Rotational usefulness proven; poaching exposure increased."
      }
    ]
  },
  "medical": [
    {
      "name": "Jalen Knox",
      "position": "Quarterback",
      "issue": "Aggravated chest-wall contusion and throwing-shoulder bruising; no structural injury",
      "status": "Expected to start",
      "plan": "Treatment Monday and Tuesday; limited Wednesday; no contact Wednesday."
    },
    {
      "name": "Isaiah Bennett",
      "position": "Cornerback",
      "issue": "Calf stable with mild swelling; repeated-burst function reduced",
      "status": "Questionable",
      "plan": "Wednesday test; no special teams; Bryce Hammond remains involved."
    },
    {
      "name": "Malik Harlan",
      "position": "Defensive Tackle",
      "issue": "Improving low-ankle sprain; lateral movement still limited",
      "status": "Questionable",
      "plan": "Possible individual work Wednesday; no team work until redirects are clean."
    },
    {
      "name": "Jonah Saye",
      "position": "Left Tackle",
      "issue": "Bruised right hand improving; no fracture",
      "status": "Expected to play",
      "plan": "Expected full practice and start with protective padding."
    },
    {
      "name": "Isaiah King",
      "position": "Running Back",
      "issue": "Mild knee swelling and workload soreness; no new injury",
      "status": "Expected to play",
      "plan": "Reduced Wednesday workload; avoid unnecessary short-yardage collisions."
    }
  ],
  "open_decisions": [
    {
      "id": "week-three-ps-protections",
      "title": "Select Week Three practice-squad protections",
      "status": "NEXT",
      "priority": "Immediate",
      "note": "This is the next required franchise action."
    },
    {
      "id": "otto-active-roster",
      "title": "Evaluate whether Otto Mbeki's H-back role warrants an active-roster spot",
      "status": "MONITOR",
      "priority": "High",
      "note": "One standard elevation remains."
    },
    {
      "id": "teo-poaching",
      "title": "Manage Teo Branković's increased poaching exposure",
      "status": "MONITOR",
      "priority": "High",
      "note": "His Week Two film validated real rotational value."
    },
    {
      "id": "knox-protection",
      "title": "Protect Jalen Knox more consistently",
      "status": "FOOTBALL CORRECTION",
      "priority": "High",
      "note": "Primary Week Three football correction."
    }
  ],
  "resources": {
    "cap": {
      "practical_flexibility_millions": 52.1595,
      "principle": "Available cap room is flexibility, not an instruction to spend."
    },
    "conditional_picks": {
      "secured_2028_sevenths": [
        "Birmingham",
        "New Orleans",
        "Carolina"
      ],
      "developing_conditions": 5
    }
  },
  "culture": {
    "victory_bow": {
      "number": 2,
      "holder": "Kendrick Holloway",
      "position": "Wide Receiver",
      "reason": "Relentless pursuit, legal recovery and advance of Marcus Vale's fumble for a touchdown, and embodiment of Finish."
    },
    "internal_standard": "Finish",
    "offensive_term": "King Push"
  }
}
$archers_state$::jsonb,
  'STL-2026-W02-CCP',
  'SEALED CANON'
)
on conflict (id) do nothing;

insert into public.archers_canon_events (
  franchise_id,
  state_version,
  event_type,
  summary,
  source_label,
  payload
)
select
  'stl-2026',
  s.version,
  'checkpoint_loaded',
  'Loaded sealed Week Two checkpoint as the Phase One starting state.',
  'CHECKPOINT',
  jsonb_build_object('checkpoint_id', 'STL-2026-W02-CCP')
from public.archers_franchise_state s
where s.id = 'stl-2026'
  and not exists (
    select 1
    from public.archers_canon_events e
    where e.franchise_id = 'stl-2026'
      and e.event_type = 'checkpoint_loaded'
      and e.payload ->> 'checkpoint_id' = 'STL-2026-W02-CCP'
  );
