\set ON_ERROR_STOP on

create role anon;
create role authenticated;
create role service_role;

create table public.archers_franchise_state (
  id text primary key,
  version integer not null default 1 check (version > 0),
  state jsonb not null,
  source_checkpoint_id text not null default 'test-checkpoint',
  seal_status text not null default 'SEALED CANON',
  updated_at timestamptz not null default now()
);

create table public.archers_canon_events (
  event_id bigint generated by default as identity primary key,
  franchise_id text not null references public.archers_franchise_state(id),
  state_version integer not null,
  event_type text not null,
  summary text not null,
  exact_kevin_text text,
  source_label text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.archers_resources (
  franchise_id text not null references public.archers_franchise_state(id),
  resource_type text not null,
  resource_id text not null,
  season integer,
  data jsonb not null default '{}'::jsonb,
  status text not null default 'ACTIVE',
  visibility text not null default 'PRIVATE',
  provenance text not null default 'LIVE_SESSION_LOG',
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  primary key (franchise_id, resource_type, resource_id)
);

create table public.archers_operation_log (
  operation_id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  operation text not null,
  resource_type text,
  resource_id text,
  expected_version integer,
  request_payload jsonb not null default '{}'::jsonb,
  result_payload jsonb not null default '{}'::jsonb,
  summary text not null,
  source_label text not null,
  exact_kevin_text text,
  state_version integer,
  status text not null default 'SUCCESS',
  created_at timestamptz not null default now()
);

create or replace function public.archers_jsonb_deep_merge(original jsonb, patch jsonb)
returns jsonb
language sql
immutable
set search_path = public
as $$
  select case
    when jsonb_typeof(original) <> 'object' or jsonb_typeof(patch) <> 'object'
      then patch
    else coalesce(
      (
        select jsonb_object_agg(key, value)
        from (
          select
            coalesce(a.key, b.key) as key,
            case
              when a.value is null then b.value
              when b.value is null then a.value
              when jsonb_typeof(a.value) = 'object' and jsonb_typeof(b.value) = 'object'
                then public.archers_jsonb_deep_merge(a.value, b.value)
              else b.value
            end as value
          from jsonb_each(original) a
          full join jsonb_each(patch) b using (key)
        ) merged
      ),
      '{}'::jsonb
    )
  end;
$$;

insert into public.archers_franchise_state (
  id,
  version,
  state,
  source_checkpoint_id,
  seal_status
) values (
  'stl-2026',
  34,
  jsonb_build_object(
    'franchise', jsonb_build_object(
      'team', 'St. Louis Archers',
      'owner_and_general_manager', 'Kevin Dorey'
    ),
    'open_decisions', jsonb_build_array(
      jsonb_build_object(
        'decision_id', 'alpha',
        'title', 'Alpha decision',
        'status', 'OPEN',
        'priority', 'NORMAL'
      ),
      jsonb_build_object(
        'decision_id', 'beta',
        'title', 'Beta decision',
        'status', 'DEFERRED',
        'priority', 'LOW'
      )
    ),
    'canon', jsonb_build_object(
      'kevin_lock', jsonb_build_object('enabled', true)
    )
  ),
  'test-checkpoint',
  'SEALED CANON'
);

insert into public.archers_resources (
  franchise_id,
  resource_type,
  resource_id,
  season,
  data,
  status,
  visibility,
  provenance,
  version
) values (
  'stl-2026',
  'decision_queue',
  'decision-queue',
  2026,
  jsonb_build_object(
    'profile_schema_version', 1,
    'queue_id', 'decision-queue',
    'summary_counts', jsonb_build_object(
      'total', 3,
      'open', 2,
      'actionable', 1,
      'deferred', 1,
      'closed', 1,
      'resolved', 1
    ),
    'decisions', jsonb_build_array(
      jsonb_build_object(
        'decision_id', 'alpha',
        'title', 'Alpha decision',
        'summary', 'Alpha is awaiting a decision.',
        'status', 'OPEN',
        'priority', 'NORMAL',
        'category', 'OTHER',
        'approval_required', true,
        'approval_owner', 'Kevin Dorey',
        'history', jsonb_build_array()
      ),
      jsonb_build_object(
        'decision_id', 'beta',
        'title', 'Beta decision',
        'summary', 'Beta is intentionally deferred.',
        'status', 'DEFERRED',
        'priority', 'LOW',
        'category', 'OTHER',
        'approval_required', true,
        'approval_owner', 'Kevin Dorey',
        'history', jsonb_build_array()
      ),
      jsonb_build_object(
        'decision_id', 'gamma',
        'title', 'Gamma decision',
        'summary', 'Gamma is already resolved.',
        'status', 'RESOLVED',
        'priority', 'NORMAL',
        'category', 'OTHER',
        'approval_required', true,
        'approval_owner', 'Kevin Dorey',
        'history', jsonb_build_array(),
        'resolution', jsonb_build_object('summary', 'Gamma was resolved earlier.')
      )
    )
  ),
  'ACTIVE',
  'CONSOLE',
  'SYSTEM',
  5
);
